### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by inodesrl** [gabrieliuga/laravel-nova-sidebar-links#5]
Hello,
I have an error when I use this addon
I attach it.
I use the example:
 public function tools()
    {
	
            (new NovaSidebar())->hydrate([
                'Utilities' => [
                    ['Telescope', '/telescope'],
                    ['Horizon', '/horizon'],
                    ['Google', 'https://google.com', '_self']
                ],
                'Google 2' => 'https://google.com'
            ]),

        ];

    }

![Cattura](https://user-images.githubusercontent.com/21054404/80194207-50bc2280-861a-11ea-9c57-faf2d11bc50d.PNG)

**Comment by gabrieliuga** [comment]
This package requires PHP version 7.4. The error is generated because I am using defined types for class properties.
```php
class NovaSidebar extends Tool
{
    use Makeable;

    public Collection $linkGroups;
    public Collection $links;
```
