### ISSUE TITLE
Wrong php version

### ISSUE THREAD

**Issue by jeffochoa** [gabrieliuga/laravel-nova-sidebar-links#6]
There is a conflict with the dependency requirements:

```
    "require": {
        "php": ">=7.4.0",
        "laravel/framework": ">=6.2",`
```
laravel framework 6 works with php7.2, see https://github.com/laravel/framework/blob/6.x/composer.json

This could be fixed by changing the  PHP version requirement to 7.2?

**Comment by gabrieliuga** [comment]
Sorry, I tend to develop all packages under latest version of PHP. The package already uses functionality from 7.4.
